---
projects:
  - id: realtime-todo-app
    secret: some-secret
    modules:
      crud:
        mongo:
          enabled: true
          conn: mongodb://localhost:27017
          collections:
            todos:
              isRealtimeEnabled: true
              rules:
                create:
                  rule: allow
                read:
                  rule: match
                  eval: ==  # Any one of them
                  type: string      # Any one of them
                  f1: args.auth.id                        # A value or variable
                  f2: args.find.userId
                update:
                  rule: allow
                delete:
                  rule: allow
        auth:
          email:
            enabled: true
        functions:
          enabled: false
          broker: nats
          conn: nats://localhost:4222
        realtime:
          enabled: true
          broker: nats
          conn: nats://localhost:4222
        fileStore:
          enabled: false
          storeType: local
          conn: ./
          rules:
            - prefix: /
              rule:
                create:
                  rule: allow
                read:
                  rule: allow
                delete:
                  rule: allow
        static:
          enabled: false
          routes:
            - path: ./public
              prefix: /
